#!/usr/bin/env python3.5

'''
py-asterisk: User interface to Asterisk.CLI.
'''

__author__ = 'David Wilson'
__id__ =     '$Id$'

import Asterisk, Asterisk.Manager, Asterisk.CLI
import sys, os, getopt




progname = os.path.basename(sys.argv[0])

try:
    sys.exit(Asterisk.CLI.command_line(sys.argv))

except Asterisk.CLI.ArgumentsError as error:
    print ( progname, 'error:', str(error), file=sys.stderr )
    Asterisk.CLI.usage(progname, sys.stderr)

except Asterisk.BaseException as error:
    print ( progname, 'error:', str(error), file=sys.stderr )

except IOError as error:
    print ( '%s: %s: %s' %\
        ( progname, error.filename, error.strerror ), file=sys.stderr )

except getopt.GetoptError as error:
    print ( '%s: %s' %\
        ( progname, error.msg ), file=sys.stderr )

    Asterisk.CLI.usage(progname, sys.stderr)
